import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { x } from "tinyexec";
import { defineConfig } from "tsdown";

export default defineConfig({
  clean: true,
  dts: {
    tsgo: true,
  },
  entry: ["src/*.ts"],
  fixedExtension: true,
  format: "iife",
  hooks: {
    "build:done": async (c) => {
      const scriptNames = c.chunks.flatMap((c) => (c.type === "chunk" ? [c.fileName] : []));

      await writeFile(
        fileURLToPath(import.meta.resolve("./server/generated-scripts.ts")),
        [
          "// This file is auto-generated by tsdown.config.ts",
          "",
          `export type ScriptName = ${JSON.stringify(scriptNames)}[number];`,
          "",
        ].join("\n"),

        "utf-8",
      );
      await x("pnpm", ["run", "format"]);
    },
  },
  minify: "dce-only",
  nodeProtocol: true,
  outDir: "dist",
  platform: "browser",
  sourcemap: true,
  treeshake: true,
  unused: {
    ignore: {
      dependencies: ["hono"],
    },
  },
});
